spring.application.name=AuthService

server.port=8080


# ===============================
# Google OAuth2 Configuration
# ===============================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,email,profile


# IMPORTANT FOR NGROK DEPLOYMENT
# Google Console redirect URI must match this exactly
spring.security.oauth2.client.registration.google.redirect-uri=https://maker-neglector-unpiloted.ngrok-free.dev/login/oauth2/code/google


# Trust forwarded HTTPS headers from ngrok
server.forward-headers-strategy=framework
server.use-forward-headers=true


# ===============================
# JWT Configuration
# ===============================

# Must be same in quantity-service
jwt.secret=MySuperSecretKeyForQuantityMeasurementApplication2026

jwt.expiration=86400000


# ===============================
# Logging
# ===============================

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
